namespace Vegan.Database.Migrations
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;
    using Vegan.Entities.Care;
    using Vegan.Entities.FoodHerb;
    using Vegan.Entities.Home;
    using Vegan.Entities.Supplement;
    using Size = Entities.Care.Size;
    

    internal sealed class Configuration : DbMigrationsConfiguration<Vegan.Database.MyDatabase>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = true;
        }

        protected override void Seed(Vegan.Database.MyDatabase context)
        {

            #region Care

            //*************************************************** Care ***************************************************

            //=================================================== FaceCream ==============================================
            //TODO We must insert face creams
            FaceCream f1 = new FaceCream() { Title = "Honey Therapy Hand and Body Lotion", Price = 19.75m, ImageURL = "https://bit.ly/2SckHKS", NameOfIngredient = "Aqua, Helianthus annuus (Sunflower) Oil, Simmondsiia chinensnsis (Jojoba) oil, Lecithin, Mangifera Indica (Mango) seed butter, Stearic Acid, Emulsifying Wax NF, Cetyl Alcohol, Vegetable Glycerine, Honey essence*, Styrax Benzoin (Benzoin), Silver Citrate, Citric Acid", ValueOfIngredient="", Directions = "Massage into dry, itchy skin as needed. For best results, exfoliate first with Moisturizing Mineral Soak to buff away dead skin and allow for maximum penetration of creme in your favourite scent.", Description = "Honey Therapy Hand and Body Lotion moisturizes and rejuvenates sad, dry skin while releasing the gentle scent of freshly baked oatmeal cookies. Nourish and comfort skin with this luscious, silky cream. We combine the healing power of organic mango butter with skin softening organic sunflower oil, jojoba and antioxidant rich Vitamin E to soothe, smooth and protect your skin from neck to toe." };
            FaceCream f2 = new FaceCream() { Title = "Hand & Body Lotion - Aegean Mint", Price = 19.75m, ImageURL = "https://bit.ly/3aOMBn2", NameOfIngredient = "Aqua, Helianthus annuus (Sunflower) Oil*, Mangifera Indica (Mango) Seed Butter*, Simmondsia chinensis (Jojoba) Oil*, Lecithin*, Palm Stearic Acid, Emulsifying Wax NF, Cetyl Alcohol, Vegetable Glycerine, organic essential oils of Spearmint, Peppermint, Rosemary, Lemon, Silver Citrate, Citric Acid.", ValueOfIngredient = "", Directions = "Massage into dry, itchy skin as needed. For best results, exfoliate first with Moisturizing Mineral Soak to buff away dead skin and allow for maximum penetration of creme in your favourite scent.", Description = "Nourish and comfort dry, itchy skin with this luscious, silky cream, richly scented with our Aegean Mint Synergy Blend of essential oils. We combine the healing power of organic mango butter with skin softening organic sunflower oil & jojoba and antioxidant rich Vitamin E to soothe, smooth and protect your skin from neck to toe. Packing a refreshing, invigorating wallop of peppermint, spearmint, lemon and rosemary, the scent of this hand & body lotion gives you a kick in the pants, in a good way." };
            FaceCream f3 = new FaceCream() { Title = "Vanilla Coconut Sunscreen SPF31 by Rocky Mountain Soap", Price = 23.00m, ImageURL = "https://bit.ly/2Se67Tf", NameOfIngredient = "Medicinal ingredients: Zinc Oxide 20.1% Non-Medicinal Ingredients: Caprylic/Capric Triglyceride, Glyceryl Isostearate, Polyhydroxystearic Acid, Aqua, Glyceryl Stearate Citrate, Cetearyl Alcohol, Glyceryl Caprylate, Glycerin*, Coco-Glucoside, Arachidyl Alcohol, Behenyl Alcohol, Arachidyl Glucoside, Natural Vanilla Flavour/Aroma, Butyrospermum Parkii (Shea Butter)*, Hectorite, Natural Coconut Flavour/Aroma, Xanthan Gum. *Organic", ValueOfIngredient = "", Directions = "Apply generously 15 minutes before sun exposure.", Description = "Enjoy the sunshine, but not the harmful rays. This SPF31, 100% natural Sunscreen Face & Body Lotion is a must for the slopes, the beach, or a jog. Non-nano Zinc Oxide provides broad-spectrum protection against damaging UVA and UVB rays penetrating the skin, while Shea Butter moisturizes your skin, making it feel amazingly soft." };
            FaceCream f4 = new FaceCream() { Title = "Hand & Body Lotion - Lemon Meringue", Price = 19.75m, ImageURL = "https://bit.ly/2zCegur", NameOfIngredient = "Aqua, Helianthus annuus (Sunflower) Oil*, Mangifera Indica (Mango) Seed Butter*, Simmondsia chinensis (Jojoba) Oil*, Lecithin*, Palm Stearic Acid, Emulsifying Wax NF, Cetyl Alcohol, Vegetable Glycerine, organic essential oils of Lemon, May Chang, Cypress Leaf, Silver Citrate, Citric Acid.", ValueOfIngredient = "", Directions = "Massage into dry, itchy skin as needed. For best results, exfoliate first with Moisturizing Mineral Soak to buff away dead skin and allow for maximum penetration of creme in your favourite scent.",  Description = "It’s a sunny, summer day; the white, linen curtains blow gently in the breeze from the open window as Grandma pulls a freshly baked lemon meringue pie from the oven. You can almost taste the fresh tartness and the light, fluffy meringue. Our Lemon Meringue Hand & Body Lotion will transport you back to a simpler time with its mouth-watering tart-sweetness and hint of nostalgia." };


            //=================================================== Hair ===================================================
            Hair h1 = new Hair() { Title = "Carina Organics Unscented Daily Moisturizing Shampoo", Price = 13.00m, ImageURL = "https://bit.ly/3bJExVO", NameOfIngredient = "Filtered Aqua, Potassium Cocoate (saponified Cocos nucifera / Coconut oil), Glycerin (vegetable), Pinus banksiana (pine) extract, Magnesium Chloride (Magnesium Oil), Olea europaea (olive) fruit oil, Matricaria chamomilla (chamomile) flower extract, Urtica dioca (nettle) leaf extract, Taraxacum officinale (dandelion) leaf extract, Trifolium pretense (clover) flower extract, Acetic Acid (Apple Cider Vinegar)", ValueOfIngredient = "", Directions = "Apply and massage evenly into wet hair. Rinse thoroughly.", Description = "A daily moisturizing shampoo formulated with certified organic plant, vegetable, flower, and tree extracts. Helps to restore lustre, volume, body, and shine.", Detail = "This product is: Synthetic Free | Hypoallergenic | Cruelty Free | Vegan | 100% Biodegradable (safe in rivers, lakes and oceans) | Paraben Free | Soy Free | Gluten Free | Dye Free" };
            Hair h2 = new Hair() { Title = "Carina Organics Unscented Daily Light Conditioner", Price = 13.00m, ImageURL = "https://bit.ly/2W0LB9O", NameOfIngredient = "Filtered Aqua, Cocos nucifera (coconut) oil, Pinus banksiana (pine) extract, Matricaria chamomilla (chamomile) flower extract, Urtica dioca (nettle) leaf extract, Taraxacum officinale (dandelion) leaf extract, Trifolium pratense (clover) flower extract, Aetic acid (apple cider vinegar), Olea europaea (olive) fruit oil, Cucurbita pepo (pumpkin) seed oil.", ValueOfIngredient = "", Directions = "Apply and massage evenly into wet hair, emphasizing any dry ends for 30 seconds. Rinse thoroughly.", Description = "A daily light conditioner formulated with certified organic plant, vegetable, flower, and tree extracts. Helps to restore lustre, softness, flexibility, and shine, while detangling hair instantly.", Detail = "This product is: Hypo Allergenic | Vegan | Cruelty Free | 100% Biodegradable (safe in rivers, lakes, streams, and oceans) | Paraben, soy, and gluten free | Made with Sustainable Palm Oil and Coconut Oil Resources" };
            Hair h3 = new Hair() { Title = "Carina Organics Unscented Leave-In Conditioner", Price = 13.00m, ImageURL = "https://bit.ly/2zyNN0F", NameOfIngredient = "Filtered Aqua, Cocos nucifera (coconut) oil, Pinus banksiana (pine) extract, Matricaria chamomilla (chamomile) flower extract, Urtica dioca (nettle) leaf extract, Taraxacum officinale (dandelion) leaf extract, Trifolium pratense (clover) flower extract, acetic acid (apple cider vinegar), Olea europaea (olive) fruit oil, Cucurbita pepo (pumpkin) seed oil.", ValueOfIngredient = "", Directions = "Spray into damp or wet hair. Comb through hair from scalp to hair follicle tips to ensure maximum moisture absorption is achieved.", Description = "A leave-in conditioner designed to naturally detangle your locks. Made with certified organic plant, vegetable, and fruit extracts. This nutrient rich, toxin-free, formulation helps to restore lustre, softness, flexibility, and shine while it detangles.", Detail = "This product is: Synthetic Free | Hypo Allergenic | Vegan | Cruelty Free | 100% Biodegradable (safe in rivers, lakes, streams, and oceans) | Paraben, soy, and gluten free | Dye Free" };
            Hair h4 = new Hair() { Title = "Carina Organics Unscented Fast Drying Hair Spray", Price = 13.00m, ImageURL = "https://bit.ly/3aFOiCT", NameOfIngredient = "Ethyl alcohol, Acacia senegal (gum) extract, Pinus banksiana (pine) extract, Matricaria chamomilla (chamomile) flower extract, Urtica dioca (nettle) leaf extract, Taraxacum officinale (dandelion) leaf extract, Trifolium pratense (clover) flower extract, Olea europaea (olive) fruit oil, Cucurbita pepo (pumpkin) seed oil.", ValueOfIngredient = "", Directions = "Spray approximately 15 cm (6 inches) from head, depressing pump with short quick strokes. Styling Tip: Spray directly at hair root for added lift. Caution: Contents are flammable, please keep away from heat or flame.", Description = "A fast drying, firm holding styling spray formulated with certified organic plant, vegetable, flower, and tree extracts. Locks hair into place, while adding extra shine - without build-up or flaking. This formulation allows you to brush out and restyle your hair at any time.", Detail = "This product is: Synthetic Free | Hypo Allergenic | Vegan | Cruelty Free | 100% Biodegradable (safe in rivers, lakes, streams, and oceans) | Paraben, soy, and gluten free | Dye Free" };
            Hair h5 = new Hair() { Title = "Carina Organics Unscented Alcohol-Free Styling Gel", Price = 13.00m, ImageURL = "https://bit.ly/2ScMlYp", NameOfIngredient = "Filtered Aqua, Acacia senegal (gum) extract, Pinus banksiana (pine) extract, Matricaria chamomilla (chamomile) flower extract, Urtica dioca (nettle) leaf extract, Taraxacum officinale (dandelion) leaf extract, Trifolium pratense (clover) flower extract, Olea europaea (olive) fruit oil, Cucurbita pepo (pumpkin) seed oil", ValueOfIngredient = "", Directions = "Dispense into palms, rub hands together and apply onto damp hair. To enhance curl definition, simply scrunch dry while using a diffuser attachment on your blow dryer.", Description = "An alcohol-free styling gel with medium to firm hold, formulated with certified organic plant, vegetable, flower, and tree extracts. Helps add volume, enhance definition or separation and also allows you to control shaping and scrunching.", Detail = "This product is: Synthetic Free | Hypo Allergenic | Vegan | Cruelty Free | 100% Biodegradable (safe in rivers, lakes, streams, and oceans) | Paraben, soy, and gluten free | Dye Free" };


            //=================================================== Lotions ================================================
            Lotion l1 = new Lotion() { Title = "Hard Working' Hand Salve", Price = 12.95m, ImageURL = "https://bit.ly/2yKIfjt", NameOfIngredient = "Olea europaea (Olive) Fruit Oil, Prunus amygdalus dulcis (Sweet Almond) Oil, Prunus armeniaca (Apricot) Kernel Oil, Simmondsia chinensis (Jojoba) Oil*, Persea gratissima (Avocado) Oil, Butyrospermum Parkii (Shea Butter) Fruit**, Beeswax*, Tocopherol (Vitamin E), Lavandula officinalis (Lavender) Oil*,Pogostemon cablin (Patchouli) Oil*, Rosmarinus officinalis (Rosemary) Leaf Extract*.", ValueOfIngredient = "", Directions = "Rub it in, and expect results!", Description = "One of our all time, best selling products! This fantastic balm protects against & alleviates chapping, cracking & roughness due to dryness. For very dry skin, slather some on at night before bedtime and slip on some nice cotton gloves to let the balm do its work while you sleep. A little of this goes a very long way!", Size = Size.Fifteen};
            Lotion l2 = new Lotion() { Title = "Vanilla Coconut Sunscreen SPF31 by Rocky Mountain Soap", Price = 23.00m, ImageURL = "https://bit.ly/2Se67Tf", NameOfIngredient = "Medicinal ingredients: Zinc Oxide 20.1% Non-Medicinal Ingredients: Caprylic/Capric Triglyceride, Glyceryl Isostearate, Polyhydroxystearic Acid, Aqua, Glyceryl Stearate Citrate, Cetearyl Alcohol, Glyceryl Caprylate, Glycerin*, Coco-Glucoside, Arachidyl Alcohol, Behenyl Alcohol, Arachidyl Glucoside, Natural Vanilla Flavour/Aroma, Butyrospermum Parkii (Shea Butter)*, Hectorite, Natural Coconut Flavour/Aroma, Xanthan Gum. *Organic", ValueOfIngredient = "", Directions = "Apply generously 15 minutes before sun exposure.", Description = "Enjoy the sunshine, but not the harmful rays. This SPF31, 100% natural Sunscreen Face & Body Lotion is a must for the slopes, the beach, or a jog. Non-nano Zinc Oxide provides broad-spectrum protection against damaging UVA and UVB rays penetrating the skin, while Shea Butter moisturizes your skin, making it feel amazingly soft.", Size = Size.Fifteen };



            //=================================================== ShaveBeard =============================================
            ShaveBeard sb1 = new ShaveBeard() { Title = "Jack Shave Cream", Price = 21.00m, ImageURL = "https://bit.ly/2Y9QMXD", NameOfIngredient = "Olea europaea (Olive) Oil, Lavendula angustifolia (Lavender) Flower Water, Aloe Barbadensis Leaf Juice, Cocos nucifera (Coconut) Oil, Butyrospermum parkii (Shea Butter) Fruit*, Theobroma cacao (Cocoa) Seed Butter*, Ricinus communis (Castor) Seed Oil, Glycerin, Beeswax, Citrus bergamia (Bergamot) oil*, Citrus limonum (Lemon) oil*, Citrus sinensis (Blood orange) oil, Styrax, Benzoin (Benzoin) oil, Piper nigrum (Black Pepper) oil*, Kaolinite (White Clay), Solum Fullonum (Fuller's Earth), Silver Citrate, Citric Acid", ValueOfIngredient = "", Directions = "Work up a rich lather using a badger hair shaving brush for ideal results.", Description = "Made from the soaps of pure olive and coconut oils, our Jack Shaving Creme delivers essential conditioning to prime the skin for shaving. The rich, warm lather provides excellent lubrication for razor glide while protecting and conditioning the skin. Enriched with organic cocoa butter, shea butter and gentle vegetable glycerin this alcohol-free formula refuses to dry out skin — even in the harshest winter weather. Try it in combination with our Shave Brush and Jack Shave Oil for a luxuriant shaving experience!", Information = "155 g, 100% All-Natural Ingredients, No artificial scents, Alcohol-free" };
            ShaveBeard sb2 = new ShaveBeard() { Title = "Jack Shave Oil", Price = 17.00m, ImageURL = "https://bit.ly/3aJdLeE", NameOfIngredient = "Helianthus annuus (Sunflower) Seed Oil*, Persea gratissima (Avocado) Oil, Vitis vinifera (Grape) Seed Oil, Simmondsia chinensis (Jojoba) Seed Oil*, Citrus bergamia (Bergamot) oil*, Citrus limonum (Lemon) oil*, Citrus sinensis (Blood orange) oil, Styrax benzoin (Benzoin) oil, Piper nigrum (Black Pepper) oil*, Tocopherol, Rosmarinus Officinalis (Rosemary) Leaf Extract*", ValueOfIngredient = "", Directions = "Use alone or under shaving cream. Apply 6-8 drops to wet skin and massage onto shaving area. Shave normally, rinsing razor often and keeping skin wet. Works great in the shower.", Description = "This all-natural shave oil is made up of 100% natural ingredients — that you can actually pronounce! By moisturizing your skin and making it easier for a razor to glide over its surface, shaving oil reduces the chance of shaving irritation, ingrown hairs and razor burn. Used in conjunction with all-natural creams or shaving soaps, a great shaving oil also eliminates harsh chemicals from your daily grooming routine. For men who shave part of their face while maintaining facial hair in other areas, shaving oil also doubles as a moisturizing product for your beard or mustache. Shaving oil can be used as a stand-alone product, but it works best when applied under lather produced by a high-quality shaving cream or applied with a shaving brush. Our Jack Shave Creme and Jack Shave Brush can be used together to enrich the shaving experience for all skin types.", Information = "60 ml, 100% Natural, No artificial fragrances, Toxin free,  Alcohol free" };
            ShaveBeard sb3 = new ShaveBeard() { Title = "Jack Shave Spritz", Price = 15.00m, ImageURL = "https://bit.ly/3cR1ZAp", NameOfIngredient = "Witch Hazel Distillate, Aqua, Glycerin, Mentha piperita (Peppermint) Flower Water, Lavandula officinalis (Lavender) Flower Water, Citrus bergamia (Bergamot) oil*, Citrus limonum (Lemon) oil*, Citrus sinensis (Blood orange) oil, Styrax benzoin (Benzoin) oil, Piper nigrum (Black Pepper) oil*", ValueOfIngredient = "", Directions = "Apply generously to your skin by spraying 4-6 times directly from the bottle. Allow to completely absorb into skin and hydrate your face. Repeat twice daily to help combat ingrown hairs and razor burn. Recommended for daily use.", Description = "This invigorating tonic treats the face and neck for a refreshing, beneficial lift! 100% free of alcohol and oils, this hydrating formula softens and conditions skin while helping combat razor burn. Mist lightly for a gentle cooling sensation. Apply generously to instantly feel revitalized and refreshed! Use in combination with our Jack Shave Oil and Jack Shave Creme for a soothing and hydrating shaving experience.", Information = "125 ml, 100% All-Natural Ingredients, No Artificial Fragrance, Toxin Free" };
            ShaveBeard sb4 = new ShaveBeard() { Title = "Beard Balm", Price = 17.00m, ImageURL = "https://bit.ly/2KEPLyW", NameOfIngredient = "Simmondsia chinensis (Jojoba) Seed Oil*, Butyrospermum Parkii (Shea Butter) Fruit**, Cocos nucifera (Coconut) oil, Beeswax, Argania spinosa (Argan) seed oil*, Citrus bergamia (Bergamot) oil*, Cedrus atlantica (Cedarwood) oil*, Boswellia carterii (Frankincense) oil, Salvia sclarea (Clary Sage) oil*, Citrus aurantifolia (Lime) oil*, Styrax benzoin (Benzoin) oil, Vetiveria zizanoides (Vetiver) oil*, Cymbopogon martini var motia (Palmarosa) oil*, Tocopherol, Rosmarinus Officinalis (Rosemary) Leaf Extract*.", ValueOfIngredient = "", Directions = "Rock your beard all day long with these simple steps: After washing, grab a fingertip amount of Beard Balm and spread on fingers. Apply to beard and massage into skin. Brush and/or comb your beard to the style you like. We recommend brushing first to spread the oil around evenly and the combing to get the shape! The end result should be a soft, moisturized beard. It s normal for it to feel slightly oily in the first 15-30 minutes after application. This is only temporary and will go away as the balm penetrates into your beard hairs.", Description = "Beard Balm is a fantastic (and necessary) tool for growing and maintaining that oh-so-handsome beard you've got going on. Keep it healthy and nourished by choosing a balm that delivers on moisturizing, sealing and styling. Jojoba and Argan oils are fantastic and key for moisturizing both your skin and your hair follicles. Both of these oils are of a high quality and have a long shelf life and will assist with strengthening and repairing damaged cell membranes and breakage in the hair shaft without clogging pores. Seal in the moisture of the jojoba and argan oils with ingredients such as shea butter and beeswax. We use both to ensure that moisture stays put where it's supposed to! The third thing a good beard balm should do is provide hold for shaping. Shaping and styling can help smooth stray hairs, tame a wild beard, or even accentuate natural curl in your beard. The same things used to seal the moisture in your beard also provide the hold for shaping and styling. Shea butter also has the added benefit of making hair follicles appear thicker, thereby making your beard appear thicker as well. ", Information = "No info available" };
            #endregion

            #region FoodHerb

            //*************************************************** FoodHerb ***********************************************
            //=================================================== Salt ===================================================
            Salt s1 = new Salt() { Title = "Celery Salt", Price = 0.70m, ImageURL = "https://bit.ly/2ScPuHE", Description = "", Information = "More info coming soon!", BulkPricing = " Price is per 10 g. To save on packaging, our herbs are sold in bulk and will arrive to you in a labelled paper bag. Now you may order as much or as little as you'd like!" };
            Salt s2 = new Salt() { Title = "Himalayan Salt, Fine", Price = 0.06m, ImageURL = "https://bit.ly/2W5x78C", Description = "", Information = "More info coming soon!", BulkPricing = "Price is per 10 g. To save on packaging, our herbs are sold in bulk and will arrive to you in a labelled paper bag. Now you may order as much or as little as you'd like!" };
            Salt s3 = new Salt() { Title = "Coarse Sea Salt", Price = 0.18m, ImageURL = "https://bit.ly/358TEp8", Description = "", Information = "More info coming soon!", BulkPricing = "Price is per 10 g. To save on packaging, our herbs are sold in bulk and will arrive to you in a labelled paper bag. Now you may order as much or as little as you'd like!" };
            Salt s4 = new Salt() { Title = "Fine Sea Salt", Price = 0.15m, ImageURL = "https://bit.ly/2SdWyUr", Description = "", Information = "More info coming soon!", BulkPricing = "Price is per 10 g. To save on packaging, our herbs are sold in bulk and will arrive to you in a labelled paper bag. Now you may order as much or as little as you'd like!" };
            Salt s5 = new Salt() { Title = "Sesoning Salt", Price = 0.52m, ImageURL = "https://bit.ly/2W6dhdg", Description = "", Information = "More info coming soon!", BulkPricing = "Price is per 10 g. To save on packaging, our herbs are sold in bulk and will arrive to you in a labelled paper bag. Now you may order as much or as little as you'd like!" };

            //=================================================== Spice =================================================
            Spice sp1 = new Spice() { Title = "Cajun Seasoning", Price = 1.08m, ImageURL = "https://bit.ly/35faK4L", Description = "", Information = "More info coming soon!", BulkPricing = "Price is per 10 g. To save on packaging, our herbs are sold in bulk and will arrive to you in a labelled paper bag. Now you may order as much or as little as you'd like!" };
            Spice sp2 = new Spice() { Title = "All Purpose Seasoning", Price = 1.22m, ImageURL = "https://bit.ly/3cMQQAG", Description = "", Information = "More info coming soon!", BulkPricing = "Price is per 10 g. To save on packaging, our herbs are sold in bulk and will arrive to you in a labelled paper bag. Now you may order as much or as little as you'd like!" };
            Spice sp3 = new Spice() { Title = "Chinese 5 Spice Blend", Price = 1.25m, ImageURL = "https://bit.ly/2YaQrE1", Description = "", Information = "More info coming soon!", BulkPricing = "Price is per 10 g. To save on packaging, our herbs are sold in bulk and will arrive to you in a labelled paper bag. Now you may order as much or as little as you'd like!" };
            Spice sp4 = new Spice() { Title = "Chili Power Blend", Price = 1.05m, ImageURL = "https://bit.ly/2SaMfk8", Description = "", Information = "More info coming soon!", BulkPricing = "Price is per 10 g. To save on packaging, our herbs are sold in bulk and will arrive to you in a labelled paper bag. Now you may order as much or as little as you'd like!" };
            Spice sp5 = new Spice() { Title = "Curry Powder", Price = 0.52m, ImageURL = "https://bit.ly/2YbwwVu", Description = "", Information = "More info coming soon!", BulkPricing = "Price is per 10 g. To save on packaging, our herbs are sold in bulk and will arrive to you in a labelled paper bag. Now you may order as much or as little as you'd like!" };


            //=================================================== Kitchen =========================================
            SproutingSeed ss1 = new SproutingSeed() { Title = "Sprouting Seeds", Price = 1.1m, ImageURL = "https://bit.ly/2KGUMH7", Description = "This tasty blend of organic sprouting seeds is filled with green leafy goodness, and has a crispy fresh flavor that leaves you feeling refreshed and nourished. Our Leafy Sprouting Seed mixture is an excellent blend of traditional sprouting seeds including clover, alfalfa, and radish.", Information = "Sprouting is a great, inexpensive, and delicious way to obtain valuable nutrition from plants. Sprouts contain essential nutrients, are an excellent source of enzymes, contain protein, and are easy to digest. Sprouts make an excellent snack, and work well in stir fries and salads. They have been known to spruce up pizza, are a necessary ingredient on sandwiches, and also shine inside of tortillas or as a garnish to your favorite soup.", NameOfIngredient = "Fresh seeds, leaves", ValueOfIngredient = "1, 2" };
            SproutingSeed ss2 = new SproutingSeed() { Title = "Sprouting Seeds - Wheatgrass (Organic)", Price = 0.49m, ImageURL = "https://go.aws/35f6z9k", Description = "Wheatgrass sprouting seeds allow you to grow your own fresh wheatgrass. Wheatgrass takes between twelve and fourteen days to mature, appearing much like the typical green grass found in a yard or field. Wheatgrass is not eaten directly by humans, as it is indigestible due to its fibrous nature. Instead, wheatgrass is prepared as a juice, where it may be consumed directly, or added to smoothies or other beverages for a wonderful nutritional kick at any time of day.", Information = "Wheatgrass is a popular health food that is a wonderful choice for optimum health. The juice from wheatgrass is rich in vital nutrients, containing large amounts of Vitamins A, C, E, B6, and providing the minerals iron, zinc, potassium, selenium, manganese, and copper. It is also a source of protein and dietary fiber. As a low calorie food, it may be used to support a weight-conscious diet. Sprouting is a great, inexpensive, and delicious way to obtain valuable nutrition from plants. Sprouts contain essential nutrients, are an excellent source of enzymes, contain protein, and are easy to digest. Sprouts make an excellent snack, and work well in stir fries and salads. They have been known to spruce up pizza, are a necessary ingredient on sandwiches, and also shine inside of tortillas or as a garnish to your favorite soup.", NameOfIngredient = "Fresh seeds, leaves", ValueOfIngredient = "1, 2" };
            SproutingSeed ss3 = new SproutingSeed() { Title = "Sprouting Seeds, Broccoli", Price = 1.98m, ImageURL = "https://bit.ly/2KIc46E", Description = "Price is per 10 g. To save on packaging, our herbs are sold in bulk and will arrive to you in a labelled paper bag. Now you may order as much or as little as you'd like!", Information = "More info coming soon!", NameOfIngredient = "Fresh seeds, leaves", ValueOfIngredient = "1, 2" };
            SproutingSeed ss4 = new SproutingSeed() { Title = "Sprouting Seeds, Spicy", Price = 1.74m, ImageURL = "https://bit.ly/359nmdC", Description = "Price is per 10 g. To save on packaging, our herbs are sold in bulk and will arrive to you in a labelled paper bag. Now you may order as much or as little as you'd like!", Information = "More info coming soon!", NameOfIngredient = "Fresh seeds, leaves", ValueOfIngredient = "1, 2" };



            //=================================================== Tea =====================================================
            //TODO We need information--------------------------------------------------------------------------------------------------------
            Tea t1 = new Tea() { Title = "Alpen Glow Herbal Tea", Price = 1.28m, ImageURL = "https://bit.ly/3aHgLbB", Description = "Simple and superb! The gentle, refreshing flavours of peppermint chamomile, and other alpine flowers beautifully enhance the tangy tones of berries and wild rosehip. Just as you would in one of our Rocky Mountain alpine meadows, we invite you to close your eyes, relax, and enjoy the splendour around you with a Natur’el cup of tea.", NameOfIngredient = "rosehips, nettle leaves, sage, caraway, yarrow, chamomile, wild rose buds, peppermint, schizandra berries, calendula petals", ValueOfIngredient = "1, 2, 3, 4, 5, 6, 7, 8, 9, 10", BulkPricing = "Buy as much or as little as you'd like! PRICE IS PER 10 G" };
            Tea t2 = new Tea() { Title = "Black Tea, Unblended", Price = 1.08m, ImageURL = "https://bit.ly/2VWQYXq", Description = "If you're a tea enthusiast who loves to blend their own delicious teas, this is a beautiful basic black tea to begin with. Add some herbs, essential oils or whatever else you desire for your own custom blend.", NameOfIngredient = "Premium black tea", ValueOfIngredient = "1", BulkPricing = "Buy as much or as little as you'd like! PRICE IS PER 10 G" };
            Tea t3 = new Tea() { Title = "Caramel Rooibos Herbal Tea", Price = 2.15m, ImageURL = "https://bit.ly/2yKRJey", Description = "The moment you crest the pass and see that sweet stunning view of Floe Lake's glistening waters…you've made it! That is the moment you take to sit and enjoy the view you have worked so hard to get. The moment to just be in that place a few minutes longer before making the long descent down to the water's edge. The opening bars are sweet toffee notes building to a full symphonic caramel. This organic Rooibos infusion is healthfully highlighted with calendula petals and topped with real caramel pieces.", NameOfIngredient = "Rooibos, caramel pieces (sugar, salted butter, soy lecithin, vanilla), calendula petals, natural and organic caramel flavour", ValueOfIngredient = "1, 2, 3, 4",  BulkPricing = "Buy as much or as little as you'd like! PRICE IS PER 10 G" };
            Tea t4 = new Tea() { Title = "Coconut Pouchong Oolong Tea", Price = 2.21m, ImageURL = "https://bit.ly/2KDpukx", Description = "Melt into the aroma and flavour of our rich, creamy, smooth coconut perfectly blended with Bao Zhong Pouchong. Pouchong is a very lightly oxidized tea somewhere between green tea and Oolong tea though often classified with the latter due to its lack of the sharper green tea flavours. The sweet flavor and soft texture of our Coconut Pouchong is an easy way to take your island vacation anytime. Enjoy on its own, or add almond or soy milk for extra richness.", NameOfIngredient = "Oolong tea leaves and Coconut Flavours", ValueOfIngredient = "1", BulkPricing = "Buy as much or as little as you'd like! PRICE IS PER 10 G" };
            Tea t5 = new Tea() { Title = "Creamy Earl Grey Black Tea", Price = 1.38m, ImageURL = "https://bit.ly/35affO5", Description = "Fine Earl Grey tea with a hint of vanilla and cream. This Earl Grey tea includes the classic combination of oil of bergamot with whole leaf premium black tea but takes the traditional blend one step further. With the addition of a touch of vanilla, the character of Earl Grey gets a touch of softness that produces a tea that is both sweet and fruity for a perfect taste combination. The added crème smooths out the traditional Earl Grey taste, making a cup of tea that can be served for just about any occasion.", NameOfIngredient = "Luxury Organic Black tea, Cornflower petals, Osmanthus petals, Natural flavours", ValueOfIngredient = "1, 2, 3, 4", BulkPricing = "Buy as much or as little as you'd like! PRICE IS PER 10 G" };
            Tea t6 = new Tea() { Title = "Daily Detox Herbal Tea", Price = 1.38m, ImageURL = "https://bit.ly/3bHo4kQ", Description = "The small perfectly smooth pebbles you can pick out of the Bow River have been meticulously cleaned and sanded down over time by the river's healing waters. Our Daily Detox blend is simultaneously sweet and spicy. This tea is filled with healing herbs that detoxify in a very gentle way and will support your journey towards an improved well being.", NameOfIngredient = "licorice, cinnamon, burdock root, ginger, dandelion root, fennel, aniseed, juniper berries, coriander, cardamom, black pepper, parsley, sage, cloves, turmeric", ValueOfIngredient = "1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15" , BulkPricing = "Buy as much or as little as you'd like! PRICE IS PER 10 G" };
            Tea t7 = new Tea() { Title = "Gyokuro Mizuumi Green Tea", Price = 3.87m, ImageURL = "https://bit.ly/35fagvI", Description = "Having been shade grown 20 days before harvest under a dark fabric hung above the field to prevent the full light of the sun from reaching the leaves (oishitaen shading method), this tea reveals the deep fragrance typical of shaded teas, and contains increased chlorophyll levels which results in a deeper, sweeter flavor and reduced astringency. The lush, dark green, finely shaped leaves develop an incredible Umami that will make the drinkers feel at peace while charming their taste buds with delightful sweet notes. This is one of the most premium green teas in the world and as such carries a high price point. We're certain you won't be disappointed though.", NameOfIngredient = "Green tea", ValueOfIngredient = "1", BulkPricing = "Buy as much or as little as you'd like! PRICE IS PER 10 G" };
            #endregion

            #region Home
            //*************************************************** Home******************************************************
            //=================================================== Candle ===================================================
            //TODO We need information--------------------------------------------------------------------------------------------------------
            Candle c1 = new Candle() { Title = "Honey Candles 12 Taper Beeswax Candle", Price = 9.75m, ImageURL = "https://bit.ly/3eVRI7T", Instructions = "Make sure your beeswax taper is snug and secure in a proper candle holder. If you find the wick to be too long, trim it no shorter than half an inch — anything more may cause dripping!", Description = "Simple and pure, Honey Candles® 100% Natural beeswax taper candle is a staple of the dinner table and a wonderful addition to any romantic occasion. Long-lasting, with a warm amber glow and a soft honey aroma. Like all of our 100% pure beeswax candles, the Honey Candles® 12 inch Natural taper candlestick is eco-friendly and good for your health, with absolutely no carcinogens or hazardous ingredients, wicks made with cotton, and all natural ingredients. You'll love the difference of your Natural Honey Candles® tapers." };
            Candle c2 = new Candle() { Title = "Honey Candles 3x3 Pillar Beeswax Candle", Price = 21.95m, ImageURL = "https://bit.ly/3eTSXEF", Instructions = "Beeswax pillar candles need to be burned in long enough sessions to ensure the wax pool melts out to near the edge of the candle. This ensures that the candle does not tunnel a hole down the middle. A thin mantle can be left or it can be gently folded or ‘hugged’ in towards the wick to create a level surface. These Natural Honey Candles® beeswax pillars use only non-toxic, environmentally-friendly ingredients: 100% pure Canadian beeswax, and cotton wicks. Ingredients that have no carcinogens, solvents, lead, zinc, or any other toxins found in other types of candles.", Description = "Handmade with 100% pure Canadian beeswax, the Honey Candles® Pillar is a one-of-a-kind beeswax candle. A long-lasting, warm glow that is ideal for the dinner table and every romantic occasion, you'll love the pleasant, natural scent of this pillar candle. These Natural Honey Candles® beeswax pillars use only non-toxic, environmentally-friendly ingredients: 100% pure Canadian beeswax, and cotton wicks. Ingredients that have no carcinogens, solvents, lead, zinc, or any other toxins found in other types of candles." };
            Candle c3 = new Candle() { Title = "Honey Candles 5x3 Pillar Beeswax Candle", Price = 3.2m, ImageURL = "https://bit.ly/3cRjOQ0", Instructions = "Beeswax pillar candles need to be burned in long enough sessions to ensure the wax pool melts out to near the edge of the candle. This ensures that the candle does not tunnel a hole down the middle. A thin mantle can be left or it can be gently folded or ‘hugged’ in towards the wick to create a level surface.", Description = "Handmade with 100% pure Canadian beeswax, the Honey Candles® Pillar is a one-of-a-kind beeswax candle. A long-lasting, warm glow that is ideal for the dinner table and every romantic occasion, you'll love the pleasant, natural scent of this pillar candle. These Natural Honey Candles® beeswax pillars use only non-toxic, environmentally-friendly ingredients: 100% pure Canadian beeswax, and cotton wicks. Ingredients that have no carcinogens, solvents, lead, zinc, or any other toxins found in other types of candles." };
            Candle c4 = new Candle() { Title = "Honey Candles 6 Natural Column Beeswax Candle", Price = 9.95m, ImageURL = "https://bit.ly/2yOIWs1", Instructions = "Because Honey Candles® 6 Inch Columns are wider than most candlesticks, they may not fit regular holders. Use a candle holder that is designed for a pillar, or better yet, a pillar holder with a spike. This will ensure your column will sit perfectly for burning.", Description = "Honey Candles® unique beeswax column combines the best elements of our 100% pure beeswax tubes and pillars. The column features a larger diameter compared to other candlesticks, translating into a longer-lasting burn, and a large flame that produces a magnificent golden halo. Columns are also more resistant to drafts and generally require little maintenance, making them the perfect beeswax candlesticks. Honey Candles® 6 inch column candlestick are environmentally friendly and made with 100% pure beeswax and 100% cotton wick. When you burn these candles you enjoy a soft honey aroma lofting through the room. Plus, beeswax candles produce a natural glow that very closely resembles sunlight. You'll love the unique quality of your Honey Candles® beeswax candlesticks." };


            //=================================================== Essential Oil ============================================
            EssentialOil eo1 = new EssentialOil() { Title = "5 Minutes Peace", Price = 11.50m, ImageURL = "https://bit.ly/2Y7xaDH", Description = "Take some time for yourself with this soothing, grounding blend. Especially helpful for feelings of overwhelm and anxiety. Excellent in the bath or for massage.", Information = "", Ingredient = "Lavandula officinalis (Lavender, Pelargonium graveolens (Geranium), Origanum marjorana (Marjoram), Cananga odorata (Ylang Ylang), Salvia sclarea (Clary Sage), Angelica archangelica (Angelica)", Size = BottleSize.Fifty};
            EssentialOil eo2 = new EssentialOil() { Title = "All Better", Price = 11.50m, ImageURL = "https://bit.ly/3cSiVXj", Description = "We all know (and greatly empathize with) the sounds of a baby experiencing its first cold/flu. Luckily, you are not alone in this difficult situation! Essential oils (when carefully administered and chosen) can be very helpful for alleviating symptoms of illness. We also understand the plight of the parent; where every minute counts and you don’t have time to mix up a blend for yourself. So here it is; All Better: the synergy that can help you both out in a tough time (because it works really well for adults, too.). Two kinds of Eucalyptus (the gentlest, safest chemotypes for infants) help to open up the respiratory tract and ease congestion, while Ravintsara loosens built-up mucous and battles viruses. The gentler chemotype of Thyme (linalool) helps eliminate bacteria and stimulate the immune system, while Lavender calms down that stressed-out, tiny body.", Information = "The suggested shelf life is 2-3 years under proper storage conditions.", Ingredient = "Eucalyptus radiata* & smithii* (Eucalyptus), Cinnamomum camphora (Ravintsara), Melaleuca alternifolia (Tea Tree)*, Lavandula angustifolia (Lavender)*, Thymus vulgaris ct linalol (Thyme)*", Size = BottleSize.Fifty };
            EssentialOil eo3 = new EssentialOil() { Title = "Balance Aromatic Roll On", Price = 18.00m, ImageURL = "https://go.aws/2VZvMjI", Description = "A beautiful grounding blend for any one seeking it, Balance brings with it the uplifting oils of Lemon and Lime, soothing Lavender and Geranium, and earthy Patchouli.", Information = "Use to help calm the brain and relieve stress to center deep into our core. It further helps to open up our crown and third eye chakra.", Ingredient = "Simmondsia chinensis (Jojoba)*, Pogostemon cablini (Patchouli) Oil*, Pelargonium graveolens (Geranium) Oil*, Citrus limonium (Lemon) Oil*, Citrus aurantifolia (Lime) Oil*, Lavandula angustifolia (Lavender) Oil", Size = BottleSize.Fifty };
            EssentialOil eo4 = new EssentialOil() { Title = "Balance", Price = 13.00m, ImageURL = "https://bit.ly/3bELfMG", Description = "This blend is a long-standing favourite at The Apothecary. Balance synergy brings together refreshing Lemon, Lime, and Patchouli for grounding emotion, and Lavender and Geranium to relax and soothe the nervous system. This blend brings to mind a symphony, a cohesive and truly harmonic experience. We love using this blend in just about everything; from bath bombs, to room/body mists, and in a roll on. Regardless of the method of application, Balance will work with you and your current emotional state, it is adaptable and can assist you in reaching equilibrium. This blend has such a diverse range of use that it could be considered helpful in most situations, from play rooms to office spaces.", Information = "The suggested shelf life is 2 years under proper storage conditions.", Ingredient = "Pogostemon cablini (Patchouli) Oil*, Pelargonium graveolens (Geranium) Oil*, Citrus limonium (Lemon) Oil*, Citrus aurantifolia (Lime) Oil*, Lavandula officinalis (Lavender) Oil*", Size = BottleSize.Fifty };
            EssentialOil eo5 = new EssentialOil() { Title = "Barry White", Price = 17.50m, ImageURL = "https://bit.ly/2W3JrpZ", Description = "Barry White sure knew what he was talking about so we decided to pay tribute to the romantic crooner with this blend. This blend boasts incredibly sensual ingredients like Sandalwood, Cedarwood, touches of Jasmine and Black Pepper, so this synergy is sure to set the mood! For those magical love times, diffuse 3-5 drops of this synergy, put a drop on a tissue and stick it inside your pillow case, or dilute with carrier oil of your choice for a sexy massage oil. (word to the wise: this blend also works beautifully diluted with jojoba in a rollerball as a perfume!)", Information = "", Ingredient = " Citrus reticulata (Red Mandarin)*, Citrus paradisii (Grapefruit)*, Cedrus atlantica (Cedarwood)*, Santalum album (Sandalwood)*, Vetiveria zizanoides (Vetiver), Piper nigrum (Black pepper)*, Pogostemon Cablin (Patchouli)*, Cananga odorata (Ylang ylang)*, Jasminum sambac (Jasmine)*.", Size = BottleSize.Fifty };



            //=================================================== HomeCleaning =============================================
            HomeCleaning hc1 = new HomeCleaning() { Title = "Caboo Bamboo Toilet Paper", Price = 1.85m, ImageURL = "https://bit.ly/35ceOD5", Description = "Tree free bathroom tissue made from 100% bamboo & sugarcane pulp. With the strength of bamboo & the softness of sugarcane, Caboo is the sustainable alternative to tree-based products.", Information = "LIMIT 6 PER ORDER. We have no supply issues with this product. In order to maintain continuous supply, we are applying a limit of 6 per order.", About = "Septic Safe, Fast Dissolving, Fragrance Free, BPA Free, Non-GMO Certified, Soft & Strong 2-Ply, Elemental Chlorine Free (ECF) bleaching process" };
            HomeCleaning hc2 = new HomeCleaning() { Title = "Redecker Cellulose Dish Cloths", Price = 3.50m, ImageURL = "https://bit.ly/2S9yfa8", Description = "Banish plastic from your kitchen cleaning routine by replacing your dirty old wash sponge with Redecker Cellulose Dish Cloths! Cellulose dish cloths are biodegradable and machine washable up to 60°C. They are firm when dry, but soften to a sponge-like consistency when wet. To extend the life of your cellulose cloth, hand wash with a gentle laundry soap and press flat to dry. Feel good about this natural cleaning tool, free from plastic packaging that can make its way into oceans and waterways.", Information = "16.5 cm, Materials: Untreated Beechwood, Tampico Fibre", About = "Redecker is a family-owned company based in Versmold, Germany. Founder Friedel Redecker earned his living as a brushmaker after becoming blind as a child. His inventiveness, sense of quality and persistence brought about a company that has sold high-quality, natural products for three generations. Every Redecker product is critically inspected and thoroughly tested by family members and employees before making it to our storefront in Inglewood. The Redecker line offers modern luxury in a range of hand-crafted and practical household items." };
            HomeCleaning hc3 = new HomeCleaning() { Title = "Redecker BBQ Brush", Price = 8.00m, ImageURL = "https://bit.ly/3eZSWPx", Description = "Scrub away the summer and leave your BBQ squeaky-clean with this stiff bristled brush. Fully biodegradable with a beechwood handle and brass wire bristles. You can feel good about this natural cleaning tool, free from plastic packaging that can make its way into oceans and waterways.", Information = "5 cm, Materials: Untreated Beechwood, Brass Wire", About = "about1" };
            HomeCleaning hc4 = new HomeCleaning() { Title = "l1", Price = 1.1m, ImageURL = "#1", Description = "descr1", Information = "info1", About = "Redecker is a family-owned company based in Versmold, Germany. Founder Friedel Redecker earned his living as a brushmaker after becoming blind as a child. His inventiveness, sense of quality and persistence brought about a company that has sold high-quality, natural products for three generations. Every Redecker product is critically inspected and thoroughly tested by family members and employees before making it to our storefront in Inglewood. The Redecker line offers modern luxury in a range of hand-crafted and practical household items." };

            //=================================================== Kitchen ==================================================
            Kitchen k1 = new Kitchen() { Title = "Bamboo Coconut Bowl", Price = 16.00m, ImageURL = "https://bit.ly/3aP7DSx", Description = "Go nuts over this beautiful, all-natural coconut bowl! Made from hand-picked coconut shells, each bowl is cleaned, polished and finished with a durable food-safe lacquer, and accented with color. Their irregular shape is just part of their charm and appeal. With this unique coconut bowl, you can serve everything from breakfast cereal to a tasty salad. Made from reclaimed material, Bambu Coconut Bowls are appropriately tested and food-safe for all your favourite meals and lunches!", Information = "Each bowl measures 5 1/2 inches dia x. 21/2 H", Instruction = ""};
            Kitchen k2 = new Kitchen() { Title = "Bamboo Pot Scraper", Price = 4.25m, ImageURL = "https://bit.ly/3bIg4A1", Description = "Bamboo pot scrapers are an essential tool in every kitchen! Hand-crafted from USDA certified organic bamboo, these pot scrapers are well shaped to get into a variety of hard-to-reach spots. The compact size fits perfectly in your hand to help remove stubborn foods and substances without scratching your cooking surface. Perfect for teflon pans or for removing baked-on substances from sensitive surfaces.", Information = "Size: 2.75, Weight: 0.4 oz each, Lightweight and more durable than wood, Made without glues or lacquers", Instruction = "Not recommended for microwave or dishwasher. Hand wash for longer life and avoid prolonged soaking. We recommend using a bamboo wood finishing oil to keep your bamboo beautiful for years to come." };
            Kitchen k3 = new Kitchen() { Title = "Bamboo Small Tongs", Price = 7.00m, ImageURL = "https://bit.ly/2y4ds0V", Description = "Grab it, flip it, toss it! These small bamboo tongs are perfect for serving appetizers, handling cocktail garnishes and picking toast out of the toaster. Also great for grabbing soaps, bath bombs and tub truffles. Crafted from USDA certified organic bamboo, these tongs are hand-burnished to a naturally smooth finish.", Information = "Size: 9inch. large tongs, Lightweight and more durable than wood, Made without glues or lacquers, Won't scratch cooking surfaces", Instruction = "Not recommended for microwave or dishwasher. Hand wash for longer life and avoid prolonged soaking. We recommend using a bamboo wood finishing oil to keep your bamboo beautiful for years to come." };
            #endregion

            #region Supplement

            //*************************************************** Supplement ***********************************************
            //=================================================== PowerHealth ==============================================
            //TODO Information and Translate
            PowerHealth ph1 = new PowerHealth() { Title = "LivaPure", Price = 21.50m, ImageURL = "https://bit.ly/3f49Vk3", Description = "Το LivaPure της σειράς Platinum Range από την Power Health αποτελεί την πλατινένια σας επιλογή  με εκχύλισμα σπόρων γαϊδουράγκαθου που αποδίδει 240mg σιλυμαρίνης, βιταμίνες (Β6, Β12, φολικό οξύ) και χολίνη.", NameOfIngredient = "Milk Thistle, Χολίνη, Ασβέστιο, Βιταμίνη Β6, Βιταμίνη Β12, Φολικό οξύ", ValueOfIngredient = "300mg, 150mg, 120mg, 0,28mg, 0,5mg, 40mg", UseInstruction = "1 δισκίο την ημέρα μετά το γεύμα." };
            PowerHealth ph2 = new PowerHealth() { Title = "Aloe Vera Juice", Price = 30.25m, ImageURL = "https://bit.ly/3cSSh0p", Description = "Γνωστή και ως Aloe vera, η αλόη είναι φυτό το οποίο περιέχει πάνω από 70 θρεπτικά συστατικά όπως βιταμίνες Α, C, E, Β1, Β2, Β3, B6, φυλλικό οξύ, χολίνη, μέταλλα, ιχνοστοιχεία, ενώ είναι ένα από τα λίγα φυτά που περιέχει τη βιταμίνη Β12. Η Power Health αξιοποιεί τις μοναδικές ιδιότητες της αλόης με το Aloe Vera Juice! Το Aloe Vera Juice της Power Health είναι ένας υψηλής περιεκτικότητας, γρήγορης επεξεργασίας χυμός αλόης, πιστοποιημένος για την ποιότητα και την καθαρότητά του.", NameOfIngredient = "Xυμός Αλόης (99,7%), σορβικό κάλιο, σορβικό οξύ, κιτρικό οξύ.", ValueOfIngredient = "", UseInstruction = "Ενήλικες: Λαμβάνεται 15ml, 1 έως 3 φορές την ημέρα πριν από το γεύμα, αφού αναμιχθεί με νερό ή χυμό φρούτου. Διατηρείται σε δροσερό χώρο. Φυλάσσεται στο ψυγείο αφού ανοιχθεί. Να μη γίνεται υπέρβαση της συνιστώμενης ημερήσιας δόσης. Τα συμπληρώματα διατροφής δεν πρέπει να χρησιμοποιούνται ως υποκατάστατο μίας ισορροπημένης δίαιτας. Το προϊόν αυτό δεν προορίζεται για την πρόληψη, αγωγή ή θεραπεία ανθρώπινης νόσου." };
            PowerHealth ph3 = new PowerHealth() { Title = "Aloe Extra", Price = 15.00m, ImageURL = "https://bit.ly/3aQuSM1", Description = "Γευτείτε τις ευεργετικές ιδιότητες της αλόης σε ένα υπέροχο προϊόν με εκπληκτική γεύση που ξεχειλίζει από οφέλη. Το προϊόν Aloe Extra αποτελεί ένα μοναδικό συνδυασμό αλόης, βιταμίνης C και βιταμίνης B6. Ένα συμπλήρωμα διατροφής με συμπυκνωμένο εκχύλισμα καθαρής αλόης που προσφέρει όλες τις ευεργετικές ιδιότητες του φυτού.", NameOfIngredient = "Aloe, βιταμίνη C, βιταμίνη B6, ", ValueOfIngredient = "500mg, 40mg, 0,7mg", UseInstruction = "Λαμβάνετε 1 αναβράζον δισκίo την ημέρα, διαλυμένο σε ένα ποτήρι νερό, κατά προτίμηση προ γεύματος, ως συμπλήρωμα διατροφής." };
            PowerHealth ph4 = new PowerHealth() { Title = "Floradix Gallexier", Price = 23.3m, ImageURL = "https://bit.ly/2Y9ghbL", Description = "Πόσιμο διάλυμα που περιέχει εκχυλίσματα από βρώσιμα λαχανικά και φρούτα. Η αγκινάρα είναι λαχανικό που ευδοκιμεί στην περιοχή της Μεσογείου. Τα οφέλη των πικρών συστατικών που περιέχονται στα φύλλα της αγκινάρας έχουν αναγνωριστεί και εκτιμηθεί από τον 16ο αιώνα. Το Galliexer σε υγρή μορφή περιέχει μεταξύ άλλων αγκινάρα, πικραλίδα, κουρκουμά και άλλα “ πικρά” φυτά όπως γεντιανή και τζίντζερ. Το Galliexer είναι κατάλληλο για χορτοφάγους που δεν μπορούν να καταναλώσουν προϊόντα ζωϊκής προέλευσης.", NameOfIngredient = "Υδατικό εκχύλισμα φυτών (75%) από: φύλλο αγκινάρας (Cynara scolymus), φύλλο πικραλίδας (Taraxacum officinale), ρίζα γεντιανής (Gentiana lutea), ρίζα κουρκουμά (Curcuma longa), εναέρια τμήματα αγριαψιθιάς (Achillea millefolium), ρίζα τζίντζερ (Zingiber officinale), λουλούδι χαμομηλιού (Matricaria recutita), καρπό μάραθου (Foeniculum vulgare), φλούδα νεραντζιού (Citrus aurantium), βότανο αγιάγκαθου (Cnicus benedictus), καρπός κάρδαμου (Elettaria cardamomum), φύλλο φλισκουνιού (Menyanthes trifoliata), σιρόπι φρουκτόζης. ", ValueOfIngredient = "Φύλλο Πικραλίδας 2.1 g, Φύλλο Αγκινάρας 6.5 g, Ρίζα Γεντιανής 1.6 g, Ρίζα Κουρκουμά 1.2 g, Ρίζα Τζίντζερ 0.8 g, Καρπό Κάρδαμου 0.2 g", UseInstruction = "Ενήλικες και παιδιά άνω των 12 ετών: Μία φορά την ημέρα από 20 ml πριν ή μετά το γεύμα." };

            //=================================================== SuperFood ================================================
            //TODO Information
            SuperFood sf1 = new SuperFood() { Title = "SLEEP MOOD", Price = 13.00m, ImageURL = "https://bit.ly/2VM44rY", Description = "The enhance formula of SUPERFOODS SLEEP MOOD combines into a superfoods blend of Passionflower, California poppy, Jujube fruit, natural 5-HTP and Melatonine which all contributes to the reduction of time for normal sleep.", NameOfIngredient = "Griffonia Simplicifolia-5HTP, Melatonin, Eschscholziae californica, Passiflora incarnata, Ziziphus jujube", ValueOfIngredient = "1, 2, 3, 4, 5" };
            SuperFood sf2 = new SuperFood() { Title = "OMEGADVANCE", Price = 22.70m, ImageURL = "https://bit.ly/3bLs9Vk", Description = "SUPERFOODS OMEGADVANCE is high in omega-3 fatty acids, especially EPA (eicosapentaenoic acid) and DHA (docosahexaenoic acid), which act synergistically, contributing to the maintenance of normal vision, to the normal function of the heart and brain function. Also contains vitamin A which contributes to the maintenance of normal vision, vitamin E which contributes to the protection of cells from oxidative stress, as well as vitamin D, which contributes to the maintenance of normal bones.", NameOfIngredient = "Vitamin A, D & E", ValueOfIngredient = "1, 2" };
            SuperFood sf3 = new SuperFood() { Title = "MEMOACT PLUS", Price = 30.00m, ImageURL = "https://bit.ly/2KGtGQy", Description = "SUPERFOODS NATURE’S BEST® MEMOACTPLUS  is suitable for men and women over 50 years and for people with intense mental needs. It contains Cocoa seed, Eleutherococcus (Siberian Ginseng), Green tea, Coenzyme Q10, a natural vitamin B complex and Zinc which contribute normal functioning of the nervous system,normal mental performance and normal cognitive function.", NameOfIngredient = "Green Tea, Cocoa Seed Eleutherococcus, Coenzyme Q10, B-complex, Zinc Malvaceae, Araliaceae, Theaceae, Elaegnaceae", ValueOfIngredient = "1, 2, 3, 4, 5, 6, 7, 8" };
            SuperFood sf4 = new SuperFood() { Title = "PROVIOMAX", Price = 20.00m, ImageURL = "https://bit.ly/3bMdnh5", Description = "The unique formula of SUPERFOODS NATURE’S BEST® PROVIOMAX contains 6 billion live cultures of 6 strains (probiotics) with Inulin (Prebiotic) which improves the viability of probiotics (Synbiotic). The enhanced formula with Selenium contributes to the normal function of the immune system. The acid resistant capsule resists stomach acid better than standard capsules to help deliver ingredients to the intestine.", NameOfIngredient = "Inulin (Prebiotic)", ValueOfIngredient = "1" };
            SuperFood sf5 = new SuperFood() { Title = "HIPPOPHAES WOMAN", Price = 19.00m, ImageURL = "https://bit.ly/35dI1gX", Description = "SUPERFOODS NATURE’S BEST HIPPOPHAES WOMAN is suitable for the women’s needs, it contains a unique combination of Sea buckthorn, Ginger, Black cohosh, Rhodiola, Red clover, Magnesium and Vitamins Α, D, E which contribute to the normal function of the immune system, maintenance of healthy bones and teeth, normal iron metabolism and the protection of cells from oxidative stress.", NameOfIngredient = "Hippophae rhamnoides, Zingiber officinale, Actea racemose L, Rhodiola Rosea radix, Trifolium pretense, Magnesium, Resveratrol, Vitamin E, Vitamin A, Vitamin D3", ValueOfIngredient = "" };
            #endregion



            //*************************************************** Care ***************************************************
            context.FaceCreams.AddOrUpdate(x => x.Title, f1, f2, f3, f4);
            context.Hairs.AddOrUpdate(x => x.Title, h1, h2, h3, h4, h5);
            context.Lotions.AddOrUpdate(x => x.Title, l1, l2);
            context.ShaveBeards.AddOrUpdate(x => x.Title, sb1, sb2, sb3, sb4);
            //*************************************************** FoodHerb ***********************************************
            context.Salts.AddOrUpdate(x => x.Title, s1, s2, s3, s4, s5);
            context.Spices.AddOrUpdate(x => x.Title, sp1, sp2, sp3, sp4, sp5);
            context.SproutingSeeds.AddOrUpdate(x => x.Title, ss1, ss2, ss3, ss4);
            context.Teas.AddOrUpdate(x => x.Title, t1, t2, t3, t4, t5, t6, t7);
            //*************************************************** Home ***************************************************
            context.Candles.AddOrUpdate(x => x.Title, c1, c2, c3, c4);
            context.EssentialOils.AddOrUpdate(x => x.Title, eo1, eo2, eo3, eo4, eo5);
            context.HomeCleanings.AddOrUpdate(x => x.Title, hc1, hc2, hc3, hc4);
            context.Kitchens.AddOrUpdate(x => x.Title, k1, k2, k3);
            //*************************************************** Supplement *********************************************
            context.PowerHealths.AddOrUpdate(x => x.Title, ph1, ph2, ph3, ph4);
            context.SuperFoods.AddOrUpdate(x => x.Title, sf1, sf2, sf3, sf4, sf5);


            context.SaveChanges();
        }
    }
}
